apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  managedFields:
  name: cronapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: testcronjob/
    repoURL: https://github.com/ashishamway/sample-app-deployment
  syncPolicy:
    syncOptions:
    - PruneLast=true
