apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld
  # annotations:
  #   argocd.argoproj.io/ignore: "true"  
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels: 
        cronjob: helloworld
    spec:
      template:
        metadata:
          labels: 
            cronjob: helloworld
        spec:
          containers:
          - name: helloworld
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; sleep 60; date; exit 1;
          restartPolicy: Never
