apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronapp
  namespace: argocd
  labels:
    app.kubernetes.io/name: cronapp-local-cluster
    app.kubernetes.io/version: HEAD
    app.kubernetes.io/managed-by: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cronjob/
    repoURL: https://github.com/ashishamway/sample-app-deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
