apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      # containers:
      # - name: sleep
      #   image: alpine:latest
      #   command: ["echo", "post-sync"]
      containers:
      - name: slack-notification
        image: curlimages/curl
        command: ["curl", "https://slack.com/api/chat.postMessage"]
        args: ["-X", "POST", "-d", '{"channel": "test-ashish"}', "-d", '{"text": "Job Finished."}', "-H", "Authorization: Bearer xoxb-"]        
      restartPolicy: Never
  backoffLimit: 0